/**
 * Base de Datos de Productos Iniciales para Running Shoes
 * 
 * Contiene información de las 6 marcas principales y sus zapatillas representativas.
 * Este archivo sirve como catálogo inicial y como sistema de respaldo (fallback) 
 * cuando la tienda no está conectada activamente a Firebase Firestore.
 */

const INITIAL_BRANDS = [
  {
    id: "nike",
    name: "Nike",
    tagline: "Just Do It — Innovación y Velocidad",
    logoText: "NIKE",
    image: "assets/images/brand_nike.jpg",
    coverColor: "linear-gradient(135deg, #111827 0%, #000000 100%)",
    description: "Líder mundial en tecnología deportiva, amortiguación Air Zoom y espumas supercríticas ZoomX."
  },
  {
    id: "adidas",
    name: "Adidas",
    tagline: "Impossible Is Nothing — Rendimiento Alemán",
    logoText: "ADIDAS",
    image: "assets/images/brand_adidas.jpg",
    coverColor: "linear-gradient(135deg, #0f172a 0%, #020617 100%)",
    description: "Zapatillas con la célebre tecnología Boost y placas de carbono Lightstrike Pro."
  },
  {
    id: "new-balance",
    name: "New Balance",
    tagline: "Run Your Way — Amortiguación y Confort Supremo",
    logoText: "NEW BALANCE",
    image: "assets/images/brand_newbalance.jpg",
    coverColor: "linear-gradient(135deg, #172554 0%, #090d16 100%)",
    description: "Pioneros en pisada suave con su espuma Fresh Foam X y ajuste ergonómico."
  },
  {
    id: "asics",
    name: "ASICS",
    tagline: "Anima Sana In Corpore Sano — Estabilidad Japonesa",
    logoText: "ASICS",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    coverColor: "linear-gradient(135deg, #1e1b4b 0%, #070913 100%)",
    description: "Referente global en absorción de impactos con tecnología PureGEL y FF BLAST+."
  },
  {
    id: "puma",
    name: "Puma",
    tagline: "Forever Faster — Agilidad y Respuesta Nitro",
    logoText: "PUMA",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80",
    coverColor: "linear-gradient(135deg, #1c1917 0%, #090807 100%)",
    description: "Revolución en carrera con espumas inyectadas con nitrógeno NITRO Foam."
  },
  {
    id: "reebok",
    name: "Reebok",
    tagline: "Life Is Not a Spectator Sport — Resistencia y Estilo",
    logoText: "REEBOK",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    coverColor: "linear-gradient(135deg, #18181b 0%, #09090b 100%)",
    description: "Ligereza legendaria en la saga Floatride Energy para entrenamientos diarios."
  }
];

const INITIAL_PRODUCTS = [
  // NIKE
  {
    id: "nike-pegasus-41",
    brandId: "nike",
    brandName: "Nike",
    name: "Nike Pegasus 41",
    category: "Daily Trainer",
    priceCOP: 489900,
    priceFormatted: "$489.900 COP",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    description: "Un ícono de la carrera diaria. Combina unidades Air Zoom duales con espuma ReactX responsiva para un retorno de energía superior y pisada reactiva.",
    weight: "280 g",
    drop: "10 mm",
    cushioning: "Alta / Reactiva",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Más Vendido",
    featured: true
  },
  {
    id: "nike-invincible-3",
    brandId: "nike",
    brandName: "Nike",
    name: "Nike ZoomX Invincible Run 3",
    category: "Máxima Amortiguación",
    priceCOP: 629900,
    priceFormatted: "$629.900 COP",
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80",
    description: "Máxima amortiguación para proteger tus articulaciones en los fondos más largos. Capa generosa de espuma supercrítica ZoomX y capellada Flyknit súper respirable.",
    weight: "310 g",
    drop: "9 mm",
    cushioning: "Ultra Suave",
    sizes: ["39", "40", "41", "42", "43", "44"],
    badge: "Top Amortiguación",
    featured: true
  },
  {
    id: "nike-air-max-270",
    brandId: "nike",
    brandName: "Nike",
    name: "Nike Air Max 270 Sport",
    category: "Casual & Training",
    priceCOP: 429900,
    priceFormatted: "$429.900 COP",
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80",
    description: "Unidad Air Max gigante en el talón que brinda comodidad sin igual durante todo el día, ideal para trotes suaves, caminatas y entrenamiento en gimnasio.",
    weight: "295 g",
    drop: "8 mm",
    cushioning: "Air Cushion",
    sizes: ["38", "39", "40", "41", "42"],
    badge: "Estilo & Confort",
    featured: false
  },
  {
    id: "nike-revolution-7",
    brandId: "nike",
    brandName: "Nike",
    name: "Nike Revolution 7",
    category: "Iniciación",
    priceCOP: 319900,
    priceFormatted: "$319.900 COP",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
    description: "Amortiguación suave y diseño versátil para quienes inician en el mundo del running. Suela de tracción duradera y malla respirable.",
    weight: "265 g",
    drop: "10 mm",
    cushioning: "Media",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Mejor Precio",
    featured: false
  },

  // ADIDAS
  {
    id: "adidas-ultraboost-5",
    brandId: "adidas",
    brandName: "Adidas",
    name: "Adidas Ultraboost 5",
    category: "Máxima Amortiguación",
    priceCOP: 599900,
    priceFormatted: "$599.900 COP",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
    description: "La evolución de la comodidad extrema. Mediasuela Boost Light renovada con mayor retorno de energía y tejido Primeknit adaptable como un media.",
    weight: "290 g",
    drop: "10 mm",
    cushioning: "Boost Premium",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Icono Comfort",
    featured: true
  },
  {
    id: "adidas-adizero-boston-12",
    brandId: "adidas",
    brandName: "Adidas",
    name: "Adidas Adizero Boston 12",
    category: "Ritmicos & Tempo",
    priceCOP: 549900,
    priceFormatted: "$549.900 COP",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80",
    description: "Zapatilla de entrenamiento rápido inspirada en la maratón de Boston. Varillas de fibra de vidrio Energyrods 2.0 y combinación de Lightstrike Pro.",
    weight: "267 g",
    drop: "7 mm",
    cushioning: "Reactiva / Carbono",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Velocidad",
    featured: true
  },
  {
    id: "adidas-supernova-rise",
    brandId: "adidas",
    brandName: "Adidas",
    name: "Adidas Supernova Rise",
    category: "Daily Trainer",
    priceCOP: 439900,
    priceFormatted: "$439.900 COP",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80",
    description: "Diseñada para la comodidad en el rodaje diario. Presenta la nueva espuma Dreamstrike+ para transiciones fluidas de talón a punta.",
    weight: "275 g",
    drop: "10 mm",
    cushioning: "Suave",
    sizes: ["39", "40", "41", "42", "43", "44"],
    badge: "Recomendado",
    featured: false
  },
  {
    id: "adidas-duramo-sl",
    brandId: "adidas",
    brandName: "Adidas",
    name: "Adidas Duramo SL",
    category: "Iniciación",
    priceCOP: 299900,
    priceFormatted: "$299.900 COP",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    description: "Ligera y estable para tus primeros 5K y 10K. Mediasuela Lightmotion muy suave y exterior de malla sintética transpirable.",
    weight: "250 g",
    drop: "9.5 mm",
    cushioning: "Ligera",
    sizes: ["38", "39", "40", "41", "42"],
    badge: "Económico",
    featured: false
  },

  // NEW BALANCE
  {
    id: "nb-1080v14",
    brandId: "new-balance",
    brandName: "New Balance",
    name: "New Balance Fresh Foam X 1080v14",
    category: "Máxima Amortiguación",
    priceCOP: 619900,
    priceFormatted: "$619.900 COP",
    image: "assets/images/brand_newbalance.jpg",
    description: "La joya de la corona en suavidad. La versión 14 ofrece una plataforma más ancha y mayor volumen de Fresh Foam X para tragar kilómetros sin fatiga.",
    weight: "292 g",
    drop: "6 mm",
    cushioning: "Nube Ultra Suave",
    sizes: ["39", "40", "41", "42", "43", "44"],
    badge: "Top Ventas NB",
    featured: true
  },
  {
    id: "nb-860v14",
    brandId: "new-balance",
    brandName: "New Balance",
    name: "New Balance Fresh Foam X 860",
    category: "Estabilidad",
    priceCOP: 499900,
    priceFormatted: "$499.900 COP",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80",
    description: "Soporte confiable para pronadores o corredores que buscan guía en la pisada. Estabilidad estructurada con confort de espuma continua.",
    weight: "305 g",
    drop: "10 mm",
    cushioning: "Estable / Media",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Soporte Pisada",
    featured: false
  },
  {
    id: "nb-565",
    brandId: "new-balance",
    brandName: "New Balance",
    name: "New Balance 565 Sport",
    category: "Casual & Sport",
    priceCOP: 369900,
    priceFormatted: "$369.900 COP",
    image: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80",
    description: "Diseño clásico retro-running reforzado con espuma EVA inyectada y talón estabilizador de TPU.",
    weight: "320 g",
    drop: "12 mm",
    cushioning: "Firme",
    sizes: ["38", "39", "40", "41", "42"],
    badge: "Clásico Retro",
    featured: false
  },
  {
    id: "nb-574",
    brandId: "new-balance",
    brandName: "New Balance",
    name: "New Balance 574 Core Run",
    category: "Iconic Sport",
    priceCOP: 389900,
    priceFormatted: "$389.900 COP",
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80",
    description: "El modelo más icónico de la marca adaptado para el ritmo urbano diario con suela ENCAP duradera y capellada en gamuza y malla.",
    weight: "315 g",
    drop: "10 mm",
    cushioning: "Confort Diario",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Atemporal",
    featured: true
  },

  // ASICS
  {
    id: "asics-nimbus-26",
    brandId: "asics",
    brandName: "ASICS",
    name: "ASICS Gel-Nimbus 26",
    category: "Máxima Amortiguación",
    priceCOP: 649900,
    priceFormatted: "$649.900 COP",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    description: "La máxima experiencia de flotación. Incorpora PureGEL en el talón y espuma FF BLAST+ ECO para aterrizajes ridículamente suaves.",
    weight: "305 g",
    drop: "8 mm",
    cushioning: "Máxima Flotación",
    sizes: ["39", "40", "41", "42", "43", "44"],
    badge: "Favorito Maratonistas",
    featured: true
  },
  {
    id: "asics-novablast-4",
    brandId: "asics",
    brandName: "ASICS",
    name: "ASICS Novablast 4",
    category: "Rebote & Entrenamiento",
    priceCOP: 539900,
    priceFormatted: "$539.900 COP",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80",
    description: "Sensación de trampolín en cada zancada. Geometría de mediasuela en forma de rombo con espuma FF BLAST PLUS ECO super elástica.",
    weight: "260 g",
    drop: "8 mm",
    cushioning: "Rebote Dinámico",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Top Rebote",
    featured: true
  },
  {
    id: "asics-kayano-30",
    brandId: "asics",
    brandName: "ASICS",
    name: "ASICS Gel-Kayano 30",
    category: "Estabilidad Premium",
    priceCOP: 639900,
    priceFormatted: "$639.900 COP",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
    description: "Sistema 4D GUIDANCE SYSTEM que proporciona estabilidad adaptativa a medida que la fatiga aparece en la carrera.",
    weight: "303 g",
    drop: "10 mm",
    cushioning: "Estable / Suave",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Control de Pisada",
    featured: false
  },
  {
    id: "asics-gt2000-12",
    brandId: "asics",
    brandName: "ASICS",
    name: "ASICS GT-2000 12",
    category: "Estabilidad Versátil",
    priceCOP: 479900,
    priceFormatted: "$479.900 COP",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    description: "Soporte ligero y ágil para media maratón. Tecnología 3D GUIDANCE y suela de tracción AHARPLUS súper resistente.",
    weight: "270 g",
    drop: "8 mm",
    cushioning: "Media / Firme",
    sizes: ["38", "39", "40", "41", "42"],
    badge: "Gran Valor",
    featured: false
  },

  // PUMA
  {
    id: "puma-deviate-nitro-2",
    brandId: "puma",
    brandName: "Puma",
    name: "Puma Deviate Nitro 2",
    category: "Carbono & Velocidad",
    priceCOP: 589900,
    priceFormatted: "$589.900 COP",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80",
    description: "Placa de fibra de carbono PWRPLATE combinada con espuma inyectada de nitrógeno NITRO Elite para propulsion imparable.",
    weight: "260 g",
    drop: "6 mm",
    cushioning: "Placa Carbono",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Placa de Carbono",
    featured: true
  },
  {
    id: "puma-velocity-nitro-3",
    brandId: "puma",
    brandName: "Puma",
    name: "Puma Velocity Nitro 3",
    category: "Daily Trainer",
    priceCOP: 429900,
    priceFormatted: "$429.900 COP",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
    description: "Considerada una de las mejores zapatillas versátiles del mercado. Suela de agarre PumaGrip imbatible en mojado y seco.",
    weight: "264 g",
    drop: "10 mm",
    cushioning: "Nitro Balanceada",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Agarre Total",
    featured: true
  },
  {
    id: "puma-foreverrun-nitro",
    brandId: "puma",
    brandName: "Puma",
    name: "Puma ForeverRun Nitro",
    category: "Estabilidad",
    priceCOP: 499900,
    priceFormatted: "$499.900 COP",
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=80",
    description: "Guía de pisada innovadora con plantilla de alineación biomecánica y doble densidad de espuma NITRO.",
    weight: "274 g",
    drop: "10 mm",
    cushioning: "Estable / Amortiguada",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Protección Articular",
    featured: false
  },

  // REEBOK
  {
    id: "reebok-floatride-energy-5",
    brandId: "reebok",
    brandName: "Reebok",
    name: "Reebok Floatride Energy 5",
    category: "Daily Trainer",
    priceCOP: 399900,
    priceFormatted: "$399.900 COP",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    description: "Famosa por su relación calidad-precio imbatible. Espuma Floatride Energy ligera, suave y súper duradera.",
    weight: "266 g",
    drop: "8 mm",
    cushioning: "Ligera & Suave",
    sizes: ["38", "39", "40", "41", "42", "43"],
    badge: "Calidad / Precio",
    featured: true
  },
  {
    id: "reebok-nano-x4",
    brandId: "reebok",
    brandName: "Reebok",
    name: "Reebok Nano X4 Run",
    category: "Cross-Training & Run",
    priceCOP: 459900,
    priceFormatted: "$459.900 COP",
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
    description: "Versión híbrida del clásico Nano adaptada para combinar entrenamientos funcionales con sprints y rodajes cortos.",
    weight: "310 g",
    drop: "7 mm",
    cushioning: "Firme & Estable",
    sizes: ["39", "40", "41", "42", "43"],
    badge: "Híbrida Gym/Run",
    featured: false
  },
  {
    id: "reebok-zig-kinetica-3",
    brandId: "reebok",
    brandName: "Reebok",
    name: "Reebok Zig Kinetica 3",
    category: "Futuristic Performance",
    priceCOP: 449900,
    priceFormatted: "$449.900 COP",
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80",
    description: "Sistema de retorno de energía Zig Energy Shell envuelto alrededor de la espuma Floatride Fuel para un estilo futurista impactante.",
    weight: "340 g",
    drop: "9 mm",
    cushioning: "Rebote Continuo",
    sizes: ["38", "39", "40", "41", "42"],
    badge: "Diseño Futurista",
    featured: true
  }
];
